<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageDescription>Shared utility extensions used internally by the GeoWerkstatt INTERLIS tools.</PackageDescription>
  </PropertyGroup>

</Project>
