// $antlr-format alignTrailingComments true, columnLimit 200, maxEmptyLinesToKeep 1, reflowComments false, useTab false
// $antlr-format allowShortRulesOnASingleLine true, allowShortBlocksOnASingleLine true, minEmptyLines 0, alignSemicolons ownLine
// $antlr-format alignColons trailing, singleLineOverrulesHangingColon true, alignLexerCommands true, alignLabels true, alignTrailers true

lexer grammar Interlis24Lexer;

channels {
    META_COMMENT
}

SEMICOLON  : ';';
COLON      : ':';
EQUAL_SIGN : '=';
COMMA      : ',';
DOT        : '.';
DOTDOT     : '..';

L_PAREN : '(';
R_PAREN : ')';
L_BRACE : '{';
R_BRACE : '}';
L_BRACK : '[';
R_BRACK : ']';

ASTERISK : '*';
PLUS     : '+';
HYPHEN   : '-';
SLASH    : '/';

DOUBLE_EQUAL  : '==';
NOT_EQUAL     : '!=' | '<>';
LESS_EQUAL    : '<=';
GREATER_EQUAL : '>=';
LESSER        : '<';
GREATER       : '>';

ARROW       : '->';
FAT_ARROW   : '=>';
DOUBLE_LEFT : '>>';
AT_SIGN     : '@';
NUMBER_SIGN : '#';
DEFINE      : ':=';
PERCENT     : '%';
TILDE       : '~';

ASSOCIATION_SYMBOL : '--';
AGGREGATION_SYMBOL : '-<>';
COMPOSITION_SYMBOL : '-<#>';

ABSTRACT              : 'ABSTRACT';
ACCORDING             : 'ACCORDING';
AGGREGATES            : 'AGGREGATES';
AGGREGATION           : 'AGGREGATION';
ALL                   : 'ALL';
AND                   : 'AND';
ANY                   : 'ANY';
ANYCLASS              : 'ANYCLASS';
ANYSTRUCTURE          : 'ANYSTRUCTURE';
ARCS                  : 'ARCS';
AREA                  : 'AREA';
AS                    : 'AS';
ASSOCIATION           : 'ASSOCIATION';
AT                    : 'AT';
ATTRIBUTE             : 'ATTRIBUTE';
ATTRIBUTES            : 'ATTRIBUTES';
BAG                   : 'BAG';
BASE                  : 'BASE';
BASED                 : 'BASED';
BASKET                : 'BASKET';
BINARY                : 'BINARY';
BLACKBOX              : 'BLACKBOX';
BLANK                 : 'BLANK';
BOOLEAN               : 'BOOLEAN';
BY                    : 'BY';
CARDINALITY           : 'CARDINALITY';
CHARSET               : 'CHARSET';
CIRCULAR              : 'CIRCULAR';
CLASS                 : 'CLASS';
CLOCKWISE             : 'CLOCKWISE';
CODE                  : 'CODE';
CONSTRAINT            : 'CONSTRAINT';
CONSTRAINTS           : 'CONSTRAINTS';
CONTEXT               : 'CONTEXT';
CONTINUE              : 'CONTINUE';
CONTINUOUS            : 'CONTINUOUS';
CONTOUR               : 'CONTOUR';
CONTRACTED            : 'CONTRACTED';
COORD                 : 'COORD';
COORD2                : 'COORD2';
COORD3                : 'COORD3';
COUNTERCLOCKWISE      : 'COUNTERCLOCKWISE';
DATE                  : 'DATE';
DATETIME              : 'DATETIME';
DEFAULT               : 'DEFAULT';
DEFERRED              : 'DEFERRED';
DEFINED               : 'DEFINED';
DEGREES               : 'DEGREES';
DEPENDS               : 'DEPENDS';
DERIVATIVES           : 'DERIVATIVES';
DERIVED               : 'DERIVED';
DIM1                  : 'DIM1';
DIM2                  : 'DIM2';
DIRECTED              : 'DIRECTED';
DOMAIN                : 'DOMAIN';
END                   : 'END';
ENUMTREEVAL           : 'ENUMTREEVAL';
ENUMVAL               : 'ENUMVAL';
EQUAL                 : 'EQUAL';
EXISTENCE             : 'EXISTENCE';
EXTENDED              : 'EXTENDED';
EXTENDS               : 'EXTENDS';
EXTERNAL              : 'EXTERNAL';
FINAL                 : 'FINAL';
FIRST                 : 'FIRST';
FIX                   : 'FIX';
FONT                  : 'FONT';
FORM                  : 'FORM';
FORMAT                : 'FORMAT';
FREE                  : 'FREE';
FROM                  : 'FROM';
FUNCTION              : 'FUNCTION';
GENERIC               : 'GENERIC';
GENERICS              : 'GENERICS';
GRADS                 : 'GRADS';
GRAPHIC               : 'GRAPHIC';
HALIGNMENT            : 'HALIGNMENT';
HIDING                : 'HIDING';
I16                   : 'I16';
I32                   : 'I32';
IDENT                 : 'IDENT';
IMPORTS               : 'IMPORTS';
IN                    : 'IN';
INHERITANCE           : 'INHERITANCE';
INSPECTION            : 'INSPECTION';
INTERLIS              : 'INTERLIS';
JOIN                  : 'JOIN';
LAST                  : 'LAST';
LINE                  : 'LINE';
LINEATTR              : 'LINEATTR';
LINESIZE              : 'LINESIZE';
LIST                  : 'LIST';
LNBASE                : 'LNBASE';
LOCAL                 : 'LOCAL';
MANDATORY             : 'MANDATORY';
METAOBJECT            : 'METAOBJECT';
MODEL                 : 'MODEL';
MTEXT                 : 'MTEXT';
MULTIAREA             : 'MULTIAREA';
MULTICOORD            : 'MULTICOORD';
MULTIPOLYLINE         : 'MULTIPOLYLINE';
MULTISURFACE          : 'MULTISURFACE';
NAME                  : 'NAME';
NO                    : 'NO';
NOINCREMENTALTRANSFER : 'NOINCREMENTALTRANSFER';
NOT                   : 'NOT';
NULL                  : 'NULL';
NUMERIC               : 'NUMERIC';
OBJECT                : 'OBJECT';
OBJECTS               : 'OBJECTS';
OF                    : 'OF';
OID                   : 'OID';
ON                    : 'ON';
OPTIONAL              : 'OPTIONAL';
OR                    : 'OR';
ORDERED               : 'ORDERED';
OTHERS                : 'OTHERS';
OVERLAPS              : 'OVERLAPS';
PARAMETER             : 'PARAMETER';
PARENT                : 'PARENT';
PERIPHERY             : 'PERIPHERY';
PI                    : 'PI';
POLYLINE              : 'POLYLINE';
PROJECTION            : 'PROJECTION';
RADIANS               : 'RADIANS';
REFERENCE             : 'REFERENCE';
REFSYS                : 'REFSYS';
REFSYSTEM             : 'REFSYSTEM';
REQUIRED              : 'REQUIRED';
RESTRICTION           : 'RESTRICTION';
ROTATION              : 'ROTATION';
SET                   : 'SET';
SIGN                  : 'SIGN';
STRAIGHTS             : 'STRAIGHTS';
STRUCTURE             : 'STRUCTURE';
SUBDIVISION           : 'SUBDIVISION';
SURFACE               : 'SURFACE';
SYMBOLOGY             : 'SYMBOLOGY';
TABLE                 : 'TABLE';
TEXT                  : 'TEXT';
THATAREA              : 'THATAREA';
THIS                  : 'THIS';
THISAREA              : 'THISAREA';
TID                   : 'TID';
TIDSIZE               : 'TIDSIZE';
TIMEOFDAY             : 'TIMEOFDAY';
TO                    : 'TO';
TOPIC                 : 'TOPIC';
TRANSFER              : 'TRANSFER';
TRANSIENT             : 'TRANSIENT';
TRANSLATION           : 'TRANSLATION';
TYPE                  : 'TYPE';
UNDEFINED             : 'UNDEFINED';
UNION                 : 'UNION';
UNIQUE                : 'UNIQUE';
UNIT                  : 'UNIT';
UNQUALIFIED           : 'UNQUALIFIED';
URI                   : 'URI';
VALIGNMENT            : 'VALIGNMENT';
VERSION               : 'VERSION';
VERTEX                : 'VERTEX';
VERTEXINFO            : 'VERTEXINFO';
VIEW                  : 'VIEW';
WHEN                  : 'WHEN';
WHERE                 : 'WHERE';
WITH                  : 'WITH';
WITHOUT               : 'WITHOUT';
XML                   : 'XML';
XMLNS                 : 'XMLNS';

fragment DIGIT    : [0-9];
fragment HEXDIGIT : DIGIT | [A-Fa-f];
fragment LETTER   : [A-Za-z];
fragment NEWLINE  : '\r'? '\n' | '\r';

EXP_NUMBER     : ('+' | '-')? '0.' ([1-9] POS_NUMBER? | '0'+) ('e' | 'E') ( SIGNED_NUMBER | POS_NUMBER);
DECIMAL_NUMBER : (SIGNED_NUMBER | POS_NUMBER) '.' POS_NUMBER;
SIGNED_NUMBER  : ('+' | '-') POS_NUMBER;
POS_NUMBER     : DIGIT+;

IDENTIFIER        : LETTER (LETTER | DIGIT | '_')*;
DOUBLE_QUOTE_OPEN : '"' -> pushMode(StringLiteral);
EXPLANATION       : '//' .*? '//';
META_COMMENT_OPEN : '!!@'                    -> channel(META_COMMENT), pushMode(MetaComment);
LINE_COMMENT      : '!!' (~[@] .*?)? NEWLINE -> channel(HIDDEN);
DOC_COMMENT       : '/**' .*? '*/'           -> channel(HIDDEN);
BLOCK_COMMENT     : '/*' .*? '*/'            -> channel(HIDDEN);
WHITESPACE        : (' ' | '\t' | NEWLINE)+  -> channel(HIDDEN);
UNEXPECTED        : .;

// Parsing string literal
mode StringLiteral;
DOUBLE_QUOTE_CLOSE : '"' -> popMode;
LITERAL_TEXT       : ~["\\]+;
BACKSLASH          : '\\\\';
DOUBLE_QUOTE       : '\\"';
UNICODE            : '\\u' HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT;
INVALID_UNICODE    : '\\u' . . . .;
UNKNOWN_ESCAPE     : '\\' .;

// Same as string literals but on other channel
mode MetaCommentStringLiteral;
META_STR_DOUBLE_QUOTE_CLOSE : '"'                                       -> channel(META_COMMENT), type(DOUBLE_QUOTE_CLOSE), popMode;
META_STR_LITERAL_TEXT       : ~["\\]+                                   -> channel(META_COMMENT), type(LITERAL_TEXT);
META_STR_BACKSLASH          : '\\\\'                                    -> channel(META_COMMENT), type(BACKSLASH);
META_STR_DOUBLE_QUOTE       : '\\"'                                     -> channel(META_COMMENT), type(DOUBLE_QUOTE);
META_STR_UNICODE            : '\\u' HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT -> channel(META_COMMENT), type(UNICODE);
META_STR_INVALID_UNICODE    : '\\u' . . . .                             -> channel(META_COMMENT), type(INVALID_UNICODE);
META_STR_UNKNOWN_ESCAPE     : '\\' .                                    -> channel(META_COMMENT), type(UNKNOWN_ESCAPE);

// Inside a meta comment
mode MetaComment;
META_COMMENT_CLOSE      : NEWLINE             -> channel(META_COMMENT), popMode;
META_WHITESPACE         : (' ' | '\t')        -> channel(HIDDEN), type(WHITESPACE);
META_ATTR_NAME          : ~[\t\f\r\n =;,"\\]+ -> channel(META_COMMENT);
META_EQUAL              : '='                 -> channel(META_COMMENT), type(EQUAL_SIGN);
META_SEMICOLON          : ';'                 -> channel(META_COMMENT), type(SEMICOLON);
META_DOUBLE_QUOTE_OPEN  : '"'                 -> channel(META_COMMENT), type(DOUBLE_QUOTE_OPEN), pushMode(MetaCommentStringLiteral);
META_COMMENT_UNEXPECTED : .                   -> channel(META_COMMENT);